# Copyright 2021 Martin Kalcok
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  self-signed-issuer-enabled:
    default: False
    description: Enable self signed issuer.
    type: boolean

  custom-ca:
    default: "{}"
    description: |
      Configuration for a custom CA. Expected format is {"crt": "<base64_cert>",
      "key": "<base64_key>"}
    type: string

  foo:
    default: False
    description: foo
    type: boolean
